services:
  postgres:
    container_name: postgres-sql-tibia-genius
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DATA: /var/lib/postgresql/data
      POSTGRES_DB: tibia_genius_db
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - network-demo
    restart: unless-stopped
  mail-dev:
    container_name: mail-dev-tibia-genius
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "1025:1025"
networks:
  network-demo:
    driver: bridge
volumes:
  postgres:
    driver: local